/*
Form the Betting Against Beta factor.
The detailed steps can be seen in the Paper which cited in the README file.
*/


proc rank data=sqbeta out=zbeta;
var sqbeta;
by tmonth;
ranks z;
run;
proc sort data=zbeta;
by tmonth stkcd;
run;
data zbeta2;
 merge zbeta stkmonth;
 by tmonth stkcd;
run;
data zbeta3;
 set zbeta2;
 keep stkcd tmonth sqbeta z Mretwd;
run;
data zbeta4;
 set zbeta3;
  if missing(sqbeta) then delete;
  if missing(z) then delete;
  if missing(Mretwd) then delete;
run;
proc sort data=zbeta4;
by tmonth z;
run;
data babtotal;
input tmonth bab;
datalines;
0 0
;
run;
%macro BAB;
%do i=38 %to 279;
data rf1;
 set rf;
 if tmonth=&i;
run;
data bab;
 set zbeta4;
 if tmonth=&i;
run;
proc sort data=bab;
 by descending z;
run;
data bab2; 
 set bab;
 retain maxz 0;
 if maxz<z then maxz=z;
run;
data k; 
 set bab2; 
 absz=abs(z-(maxz+1)/2); 
run;
proc means data=k noprint;
  var absz;
  output out=k2 sum=k;
run;
data k3;
  set k2;
  k=2/k;
  drop _TYPE_ _FREQ_;
run;
data LowBeta;
  set bab2;
  if z<=(maxz/2);
  run;
data LowBeta2;
  merge LowBeta k3;
run;
data LowBeta3;
  set LowBeta2;
  retain kk 0;
  kk=ifn(missing(k)=0,k,kk);
run;
data LowWeight;
  set LowBeta3;
  w=kk*(z-(maxz+1)/2);
  drop k kk maxz;
run;
data left;
  set LowWeight;
  left=Mretwd*w;
  cleft=sqbeta*w;
run;
proc means data=left noprint;
  var left cleft;
  output out=left2 sum=;
run;
data left3;
  set left2;
  cleft=1/cleft;
  drop _TYPE_ _FREQ_;
run;
data HighBeta;
  set bab2;
  if z>(maxz/2);
run;
data HighBeta2;
  merge HighBeta k3;
run;
data HighBeta3;
  set HighBeta2;
  retain kk 0;
  kk=ifn(missing(k)=0,k,kk);
run;
data HighWeight;
  set HighBeta3;
  w=kk*(z-(maxz+1)/2);
  drop k kk maxz;
run;
data right;
  set HighWeight;
  right=Mretwd*w;
  cright=sqbeta*w;
run;
proc means data=right noprint;
  var right cright;
  output out=right2 sum=;
run;
data right3;
  set right2;
  cright=1/cright;
  drop _TYPE_ _FREQ_;
run;
data tmonthbab;
  merge left3 right3 rf1;
  bab=cleft*(left-rf)-cright*(right-rf);
  keep tmonth bab;
run;
data babtotal;
  set babtotal tmonthbab;
run;
%end;
%mend BAB;
%BAB;
data babtotal;
 set babtotal;
  if tmonth=0 then delete;
run;
